% file: short.inc
% vim:fileencoding=utf-8:fdm=marker:ft=postscr
% Shortcuts for often used commands.
%
% Copyright © 2003 R.F. Smith <rsmith@xs4all.nl>
% SPDX-License-Identifier: MIT
% Created: 2003/01/02 17:30:13
% Last modified: 2018-05-02T21:54:08+0200

/bd {bind def} bind def
/ed {exch def} bd
/m {moveto} bd
/l {lineto} bd
/rl {rlineto} bd
/cu {curveto} bd
/rcu {rcurveto} bd
/c {closepath} bd
/bl {0 setgray} bd
/wh {1 setgray} bd
/s {stroke} bd
/f {fill} bd
/S {gsave} bd
/R {grestore} bd
/t {translate} bd
/r {rotate} bd
/cp {currentpoint} bd
/slw {setlinewidth} bd
/slc {setlinecap} bd
